### ISSUE TITLE
Can I use it with microsoft windows?

### ISSUE THREAD

**Issue by Golddouble** [chungkwong/MathOCR#1]
This project looks interesting. But what do I need to download to start MathOCR in Windows 7 32bit?

**Comment by chungkwong** [comment]
It can be used with windows since it is written in pure java. However, the program is very far from satisfactory and the developement is stopped.

At 2016-08-10 19:42:25, "Golddouble" notifications@github.com wrote:

This project looks interesting. But what do I need to download to start MathOCR in Windows 7 32bit?
